### PR TITLE
Initial update to 0.2.0 for Denizen 0.9.2, some tags nullified, mcMMO now uses latest dev builds

### PR DESCRIPTION
**Pull request by Morphan1**
New mcMMO builds - http://ci.mcmmo.org/job/mcMMO/lastSuccessfulBuild/

0.9.2 uses a new tag system, as well as a slightly different command
system. The tag system uses dObjects to allow the stringing together of
tags. However, some tags no longer make sense in this format, such as
&lt;player.town.ismayor&gt;. This can easily be replaced, however, with "- if
&lt;player.town.mayor&gt; == &lt;player&gt;"

I've noticed quite a few requests for integration with the Jobs plugin.
I'll look into that soon.

Known bug:
- The rank system is currently having an API developed in
  mcMMO, which is the main reason for using Dev Builds. As of right now,
  however, the &lt;player.mcmmo.rank&gt; tag will not work. Although there is a way to make it work,
  it would require querying the Database, which I'm told is not
  recommended.

If you notice any issues or you have any recommendations, please report
them here -> https://github.com/GnomeffinWay/Depenizen/issues/new

### CODE REVIEW

**Comment by monnierant** [comment]
I have also some tags that are nulled

player.faction  is nulled
player.faction.title is nulled
player.faction.power is nulled

but player.faction.role work perfectly.

I can't test no other one

**Comment by Morphan1** [comment]
@monnierant perfect, thanks for the feedback... I'll check it out tomorrow, it shouldn't be too much work.

**Comment by Morphan1** [comment]
@monnierant There's been a few changes...
Now, to use &lt;player.faction.role&gt;, &lt;player.faction.title&gt;, or &lt;player.faction.power&gt;, you need to simply change "player.faction" to "player.factions"

What &lt;player.faction&gt; was returning before will now be "faction@FactionName", to match the newest versions of Denizen. To get just the name, you can just do &lt;player.faction.name&gt;

**Comment by monnierant** [comment]
Thanks for your quick answer. I will test it in 11 hours (after work). Just where can i found the .jar ?

I realy apreciate your work continue in this way you are doing it right and nicely

**Comment by Morphan1** [comment]
The latest build is available here - http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/

**Comment by monnierant** [comment]
Small issue in #166 while i use <player.factions.role> and <player.factions.title> they both return "faction²mercenaire" (mercenaire is my faction name)

There is the log of issue in console

http://paste.ehck.fr/?384434ff23b6413d#/vpFAVcCUiE2E/818AqEL0dDFZd86kyeHw8cLypKcUk=

I hope all this thing will help you (i couldn't test with #167 because it could'nt pass plugin registration as i say in issue #3)

**Comment by monnierant** [comment]
Ok i have just test the #168 build and it import correctly but i always have the tag issue

player.faction.name > work
player.factions.power > work

player.faction.role > faction@Mercenaire
player.factions.role > faction@Mercenaire
player.faction.title > faction@Mercenaire
player.factions.title > faction@Mercenaire

for information Mercenaire is my faction name.

I hope all this information could help you to fix this issue.

**Comment by monnierant** [comment]
I have also test the other replacable tags

faction[mercenaire].balance=40.0
faction[mercenaire].home=faction[mercenaire].home
faction[mercenaire].isopen=false
faction[mercenaire].ispeaceful=false
faction[mercenaire].ispermanent=false
faction[mercenaire].leader=null
faction[mercenaire].playercount=9
faction[mercenaire].power=88.99999999999989
faction[mercenaire].relation[LeCerclesDesSages]=faction@Mercenaire
faction[mercenaire].size=144

i have an issue in server console when i test the 'faction[mercenaire].home'
http://paste.ehck.fr/?ccb70efc99d65ae8#IDum1bqMeG7Wyat3rTU0imJDzjEbP15/orxSdBNW2U0=

i hope all this log could help you. If i could do anything to help you more it will be a pleasure.

**Comment by Morphan1** [comment]
@monnierant try the new build... it SHOULD fix those tags
And thanks for telling me this stuff. Without you, this would probably go unnoticed for a while

**Comment by monnierant** [comment]
Thanks for the quick answer and the good job.

But it's not work this time

so this time
faction[mercenaire].balance=40.0
 faction[mercenaire].home=faction[mercenaire].home
 faction[mercenaire].isopen=false
 faction[mercenaire].ispeaceful=false
 faction[mercenaire].ispermanent=false
 faction[mercenaire].leader=null
 faction[mercenaire].playercount=9
 faction[mercenaire].power=88.99999999999989
 faction[mercenaire].relation[LeCerclesDesSages]=null
 faction[mercenaire].size=144

player.faction.name > work

 player.factions.power > null
player.faction.role > null
 player.factions.role > null
 player.faction.title > null
 player.factions.title > null

if i can help you to debug this plugin it's pretty cool. I realy like your work and i need it.

more over i also have this error too
http://paste.ehck.fr/?ddecd19cd9ebc62e#vRm3Fes6e49FkP+drHpSb8JwK3X91OqaDpVkOIMXXqQ=

**Comment by Morphan1** [comment]
Odd... &lt;player.factions.power&gt; should never return null...
But &lt;player.factions.role&gt; and &lt;player.factions.title&gt; are supposed to return null if the player doesn't have a role or title in the faction.

**Comment by monnierant** [comment]
But i testit with me a player that is OFF in faction with righthand as title (my faction is mercenaire well

**Comment by mcmonkey4eva** [comment]
GnomeffinWay is no longer active, the project has been transferred here:
https://github.com/Morphan1/Depenizen
Please report all issues there.

**Comment by Morphan1** [comment]
I'm gonna finally close this now lol...
The official Depenizen repository is now located at https://github.com/DenizenScript/Depenizen and has been for some time now

**Pull request closed without merging**
